### ISSUE TITLE
How to leverage Weaviate's build-in modules (vectoriser, summariser, etc)?

### ISSUE THREAD

**Issue by hugocool** [docarray/docarray#1591]
The current documentation for the Docarray library only covers examples where the embedding vectors are already supplied. However, it's unclear whether Docarray allows one to input text or other data and leverage Weaviate's built-in modules for vectorisation, or summarisation.
Is this possible using DocArray?

for example, one could have a setup a weaviate instance with the following `docker-compose` 
```
---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.19.6
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      TRANSFORMERS_PASSAGE_INFERENCE_API: 'http://t2v-transformers-passage:8080'
      TRANSFORMERS_QUERY_INFERENCE_API: 'http://t2v-transformers-query:8080'
      SUM_INFERENCE_API: 'http://sum-transformers:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers,sum-transformers'
      CLUSTER_HOSTNAME: 'node1'
  t2v-transformers-passage:
    image: semitechnologies/transformers-inference:facebook-dpr-ctx_encoder-single-nq-base
    environment:
      ENABLE_CUDA: '1'
      NVIDIA_VISIBLE_DEVICES: 'all'
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: 
            - 'gpu'
  t2v-transformers-query:
    image: semitechnologies/transformers-inference:facebook-dpr-question_encoder-single-nq-base
    environment:
      ENABLE_CUDA: '1'
      NVIDIA_VISIBLE_DEVICES: 'all'
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: 
            - 'gpu'
  sum-transformers:
    image: semitechnologies/sum-transformers:facebook-bart-large-cnn-1.0.0
    environment:
      ENABLE_CUDA: '1'
      NVIDIA_VISIBLE_DEVICES: 'all'
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: 
            - 'gpu'
```
And use a data model like:

```
class Article:
   id:int
   text:str
   summary:str
```

And now use docarray to store the articles in the weaviate database, and later retrieve the summaries, which are supplied by weaviate itself. Idem for embeddings.
This would obviously make one wonder whether we could do the same with search, e.g. do similarity search by only providing the word to be embedded, and allow weaviate to do the embedding and search itself.

It would be helpful to have more information on how to use Weaviate's native vectorisation modules with Docarray. Specifically, it would be useful to have examples of how to input text data and let the Weaviate database service do the embedding, and later retrieve the results.
If this currently possible with DocArray?

If it is, i'd be willing to contribute to the docs.

If it is not possible, would you consider it to be in the scope of DocArray?
